# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_auto_20160922_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertence',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
