# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_auto_20160922_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertence',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
